[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
tokio-util = { workspace = true }
bincode = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
